### ISSUE TITLE
Can't view comments to/from teacher

### ISSUE THREAD

**Issue by ThisIsMyNick** [james9909/HomeworkServer#1]
"View homeworks" doesn't let you view comments you wrote or the response from teacher.

**Comment by james9909** [comment]
Thank you for reporting this fatal issue.

**Comment by ThisIsMyNick** [comment]
It still doesn't display teacher comments. re-open pls

**Comment by james9909** [comment]
Did you update the script to the latest version?

**Comment by ThisIsMyNick** [comment]
Yep. Doesn't display teacher's comment.

**Comment by james9909** [comment]
![screenshot from 2015-10-26 00 07 47](https://cloud.githubusercontent.com/assets/9091144/10721147/9b87ddcc-7b75-11e5-9529-3a5ac7a5667b.png)

**Comment by ThisIsMyNick** [comment]
It shows your comment to the teacher, but not the teacher's comment (as a response to yours).

also, neat background

**Comment by james9909** [comment]
Wait they have those?

**Comment by ThisIsMyNick** [comment]
also, neat background

**Comment by ThisIsMyNick** [comment]
yes

**Comment by james9909** [comment]
Will leave un-fixed until Mr. Brown replies to my comment.

**Comment by james9909** [comment]
_Should_ work now.
